CITY_CRIME_CONFIG = {
    "Addison": {},
    "Balch Springs": {"source": "fbi_default"},
    "Carrollton": {},
    "Cedar Hill": {},
    "Cockrell Hill": {},
    "Combine": {},
    "Coppell": {},
    "Dallas": {"source": "socrata","dataset_id": "qv6i-rri7","has_coordinates": True},
    "DeSoto": {},
    "Duncanville": {},
    "Farmers Branch": {},
    "Ferris": {},
    "Garland": {"source": "pdf","has_coordinates": False},
    "Glenn Heights": {},
    "Grand Prairie": {},
    "Grapevine": {},
    "Highland Park": {},
    "Hutchins": {},
    "Irving": {},
    "Lancaster": {},
    "Lewisville": {},
    "Mesquite": {},
    "Ovilla": {},
    "Richardson": {},
    "Rowlett": {},
    "Sachse": {},
    "Seagoville": {},
    "Sunnyvale": {},
    "University Park": {},
    "Wilmer": {},
    "Wylie": {}
}